# Generated by Django 4.2.3 on 2024-02-22 09:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("pic", models.FileField(null=True, upload_to="media/cutomer/")),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_name", models.CharField(max_length=30)),
                ("ram", models.CharField(max_length=30)),
                ("rom", models.CharField(max_length=30)),
                ("info", models.TextField()),
                ("price", models.CharField(max_length=30)),
                ("pic", models.FileField(upload_to="media/mobile/")),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("role", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("mobile_no", models.CharField(max_length=30, null=True)),
                ("country", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("productname", models.CharField(max_length=30)),
                ("ram", models.CharField(max_length=30)),
                ("rom", models.CharField(max_length=30)),
                ("qty", models.CharField(max_length=30)),
                ("price", models.CharField(max_length=30)),
                ("total_price", models.CharField(max_length=30)),
                ("date", models.DateField(default=datetime.datetime.today)),
                ("status", models.BooleanField(default=False)),
                (
                    "cust_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecomapp.customer",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecomapp.product",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecomapp.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="cust_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecomapp.user"
            ),
        ),
    ]
