# Generated by Django 4.2.3 on 2024-02-28 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productname", models.CharField(max_length=30)),
                ("ram", models.CharField(max_length=30)),
                ("rom", models.CharField(max_length=30)),
                ("qty", models.CharField(max_length=30)),
                ("price", models.CharField(max_length=30)),
                ("total_price", models.CharField(max_length=30)),
                ("pic", models.FileField(upload_to="media/mobile/")),
                (
                    "cust_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecomapp.customer",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecomapp.product",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecomapp.user"
                    ),
                ),
            ],
        ),
    ]
